// SPDX-License-Identifier: MIT OR Apache-2.0

//! 2026-09-25: Build script for metrale-storage: links libcuda for the driver
//! FFI in `cuda_min.rs`, and compiles each `KERNELS` entry in `kernels/` to PTX,
//! registered as `STORAGE_PTX` in `OUT_DIR/storage_ptx.rs`.
//!
//! Owner: metrale-storage build.
//! Invariants:
//! - A build that completes has written `OUT_DIR/storage_ptx.rs`. On macOS,
//!   with `METRALE_SKIP_BUILD`/`SKIP_METRALE_BUILD` in {1, true, TRUE}, or with
//!   `METRALE_TARGET_HW=strix-hip`, `STORAGE_PTX` is empty and
//!   `predictor.rs` fails to load with "missing predictor kernel function".
//! - An nvcc failure panics the build.

use std::path::{Path, PathBuf};
use std::process::Command;

const KERNELS: &[&str] = &[
    "q_lowrank_project",
    "kv_lowrank_project",
    "predictor_score",
    "paged_decode_attn_tiled",
    "attention_finalize",
];

fn main() {
    println!("cargo:rerun-if-env-changed=METRALE_SKIP_BUILD");
    println!("cargo:rerun-if-env-changed=SKIP_METRALE_BUILD");
    println!("cargo:rerun-if-env-changed=METRALE_TARGET_HW");
    println!("cargo:rerun-if-env-changed=METRALE_PREDICTOR_ARCH");
    // 2026-09-25: Before any early return: `rustc-check-cfg` does not cross
    // crates, so this crate declares the cfg name itself, or every
    // `#[cfg(metrale_rdma_verbs)]` trips `unexpected_cfgs` under the workspace's
    // `warnings = "deny"`.
    println!("cargo:rustc-check-cfg=cfg(metrale_rdma_verbs)");

    // 2026-09-25: Resolved before every early return, so the fallback warning
    // is printed whether or not nvcc runs.
    let predictor_arch = resolve_predictor_arch();

    // 2026-09-25: macOS hosts have no libcuda and no nvcc: emit the stub and
    // link nothing.
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "macos" {
        emit_stub();
        println!("cargo:rerun-if-changed=build.rs");
        return;
    }

    // 2026-09-25: libcuda is linked even when the skip flag is set: examples
    // and binaries call `cuda_min` / `cuda_module` and need the symbols at link
    // time with an empty kernel registry.
    link_libcuda();
    // 2026-09-25: The RDMA verbs shim is built by metrale-gpu-sys
    // (`links = "metrale_rdma_shim"`), which prints `cargo:has_verbs=1` when it
    // compiles the shim. Cargo shows that only to direct dependents, as
    // `DEP_METRALE_RDMA_SHIM_HAS_VERBS`, and `rustc-cfg` does not cross crates,
    // so this crate re-emits the cfg. metrale-gpu-sys/build.rs decides when the
    // shim is built.
    if std::env::var("DEP_METRALE_RDMA_SHIM_HAS_VERBS").is_ok() {
        println!("cargo:rustc-cfg=metrale_rdma_verbs");
    }
    if skip_build() {
        emit_stub();
        println!("cargo:rerun-if-changed=build.rs");
        return;
    }
    // 2026-09-25: The strix-hip target has hipcc, not nvcc, and these kernels
    // are loaded as PTX text, so it gets the empty registry.
    if std::env::var("METRALE_TARGET_HW").as_deref() == Ok("strix-hip") {
        emit_stub();
        println!("cargo:rerun-if-changed=build.rs");
        return;
    }
    compile_kernels(&predictor_arch);
    println!("cargo:rerun-if-changed=build.rs");
}

fn skip_build() -> bool {
    let truthy = |key: &str| {
        matches!(
            std::env::var(key).ok().as_deref(),
            Some("1") | Some("true") | Some("TRUE")
        )
    };
    truthy("METRALE_SKIP_BUILD") || truthy("SKIP_METRALE_BUILD")
}

fn emit_stub() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let stub = "// Auto-generated by metrale-storage/build.rs (METRALE_SKIP_BUILD stub).\n\
        pub struct StoragePtx { pub name: &'static str, pub ptx: &'static str }\n\
        pub const STORAGE_PTX: &[StoragePtx] = &[];\n";
    std::fs::write(out_dir.join("storage_ptx.rs"), stub).expect("emit stub storage_ptx.rs");
}

fn link_libcuda() {
    let cuda_lib_dirs = [
        "/usr/local/cuda/targets/sbsa-linux/lib/stubs",
        "/usr/local/cuda/targets/x86_64-linux/lib/stubs",
        "/usr/local/cuda-13.0/targets/sbsa-linux/lib/stubs",
        "/usr/lib/aarch64-linux-gnu",
        "/usr/lib/x86_64-linux-gnu",
    ];
    for dir in cuda_lib_dirs {
        if Path::new(dir).is_dir() {
            println!("cargo:rustc-link-search=native={dir}");
        }
    }
    println!("cargo:rustc-link-lib=dylib=cuda");
}

fn compile_kernels(arch: &str) {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let kernels_dir = manifest_dir.join("kernels");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let nvcc = find_nvcc();

    let mut emit = String::new();
    emit.push_str("// Auto-generated by metrale-storage/build.rs.\n");
    emit.push_str("pub struct StoragePtx { pub name: &'static str, pub ptx: &'static str }\n");
    emit.push_str("pub const STORAGE_PTX: &[StoragePtx] = &[\n");

    for stem in KERNELS {
        let src = kernels_dir.join(format!("{stem}.cu"));
        let ptx_out = out_dir.join(format!("{stem}.ptx"));
        println!("cargo:rerun-if-changed={}", src.display());
        let status = Command::new(&nvcc)
            .args([
                "--ptx",
                &format!("-arch={arch}"),
                "-O3",
                "--use_fast_math",
                src.to_str().unwrap(),
                "-o",
                ptx_out.to_str().unwrap(),
            ])
            .status()
            .unwrap_or_else(|e| panic!("invoke nvcc ({}): {e}", nvcc.display()));
        if !status.success() {
            panic!("nvcc --ptx failed for {}", src.display());
        }
        // 2026-09-25: `{:?}` quotes and escapes the path. A raw Windows OUT_DIR
        // such as `D:\a\...` would put the invalid escape `\a` into the
        // generated file.
        emit.push_str(&format!(
            "    StoragePtx {{ name: \"{stem}\", ptx: include_str!({}) }},\n",
            format_args!("{:?}", ptx_out.to_string_lossy())
        ));
    }
    emit.push_str("];\n");
    std::fs::write(out_dir.join("storage_ptx.rs"), emit).expect("emit storage_ptx.rs");
}

fn find_nvcc() -> PathBuf {
    let candidates = ["/usr/local/cuda/bin/nvcc", "/usr/local/cuda-13.0/bin/nvcc"];
    for c in candidates {
        if Path::new(c).is_file() {
            return PathBuf::from(c);
        }
    }
    PathBuf::from("nvcc")
}

/// 2026-09-25: The SM architecture the storage kernels compile for:
/// `METRALE_PREDICTOR_ARCH` when set, else `[hardware].arch` from
/// `kernels/<METRALE_TARGET_HW or gb10>/HARDWARE.toml`, else `sm_121` with a
/// cargo warning.
fn resolve_predictor_arch() -> String {
    const FALLBACK: &str = "sm_121";
    if let Ok(explicit) = std::env::var("METRALE_PREDICTOR_ARCH") {
        return explicit;
    }
    let hw = std::env::var("METRALE_TARGET_HW").unwrap_or_else(|_| "gb10".to_string());
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let hardware_toml = manifest
        .parent()
        .and_then(|crates| crates.parent())
        .expect("crates/<crate> sits two levels below the workspace root")
        .join("kernels")
        .join(&hw)
        .join("HARDWARE.toml");
    println!("cargo:rerun-if-changed={}", hardware_toml.display());
    match hardware_arch(&hardware_toml) {
        Some(arch) => arch,
        None => {
            println!(
                "cargo:warning=metrale-storage: no [hardware].arch in {} — predictor kernels fall \
                 back to {FALLBACK}; set METRALE_TARGET_HW to a target under kernels/, or \
                 METRALE_PREDICTOR_ARCH to override",
                hardware_toml.display()
            );
            FALLBACK.to_string()
        }
    }
}

/// 2026-09-25: `[hardware].arch` from a `HARDWARE.toml`, or `None` if the file
/// cannot be read or parsed, or has no string `arch`.
fn hardware_arch(path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    let doc: toml::Value = toml::from_str(&text).ok()?;
    Some(doc.get("hardware")?.get("arch")?.as_str()?.to_string())
}
