// SPDX-License-Identifier: MIT OR Apache-2.0

//! 2026-09-26: What build.rs writes for the library crate besides the kernel
//! binaries: the skip stub, the generated `target_ptx.rs` and the per-target
//! closure attestation.
//!
//! Owner: metrale-kernels build.
//! Invariants:
//! - Both writers append `target_defaults_literal` to `target_ptx.rs` and
//!   emit `METRALE_KERNEL_SET_HASH` over the written content.
//!
//! Included via `#[path = "build_emit.rs"] mod build_emit;` so types from
//! build.rs (`Target`) are reachable via `super::`.

use std::env;
use std::path::{Path, PathBuf};

use super::build_codegen::generate_target_ptx_rs;
use super::{Target, build_defaults, build_diagnose, build_target, content_hash};

/// 2026-09-25: The `TARGET_DEFAULTS` and `TARGET_SM_COUNT` constants for the
/// hardware tree this build selected.
///
/// Appended to `target_ptx.rs` on both paths, the skip stub and the compiling
/// build, rather than written to a file of its own:
///
/// * the constants are configuration, not kernel blobs, and builds under
///   `METRALE_SKIP_BUILD=1` still need them;
/// * cargo does not track an `include!`d generated file as a recompile input.
///   One generated file behind one `include!` is covered by the one
///   `METRALE_KERNEL_SET_HASH`.
fn target_defaults_literal(workspace_root: &std::path::Path) -> String {
    let hw = env::var("METRALE_TARGET_HW").unwrap_or_else(|_| build_diagnose::DEFAULT_HW.into());
    let kernels_root = workspace_root.join("kernels");
    let path = kernels_root.join(&hw).join("HARDWARE.toml");
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    format!(
        "{}{}",
        build_defaults::literal(&build_defaults::read_defaults(&kernels_root, &hw)),
        build_defaults::sm_count_literal(build_defaults::read_sm_count(&kernels_root, &hw)),
    )
}

/// 2026-09-26: The skip path: write a stub `target_ptx.rs` that compiles no
/// kernel, and emit the rustc-env values the library reads.
pub(super) fn write_skip_stub(out_dir: &Path, workspace_root_owned: &Path) {
    // 2026-09-25: Stub both the cuda-side (`ptx_modules`, `all_ptx_sets`) and
    // the metal-side (`metallib_modules`) generated APIs so any
    // consumer of either keeps type-checking under the skip path.
    let stub = "// Auto-generated by build.rs (skip stub — no kernel compiler invoked).\n\
        pub fn ptx_modules() -> Vec<(&'static str, &'static [u8])> { Vec::new() }\n\
        pub fn metallib_modules() -> Vec<(&'static str, &'static [u8])> { Vec::new() }\n\
        pub fn all_ptx_sets() -> Vec<TargetPtxSet> { Vec::new() }\n";
    let stub = format!("{stub}{}", target_defaults_literal(workspace_root_owned));
    std::fs::write(out_dir.join("target_ptx.rs"), &stub).expect("write skip stub target_ptx.rs");
    println!(
        "cargo:rustc-env=METRALE_KERNEL_SET_HASH={}",
        content_hash(&stub)
    );
    println!("cargo:rustc-env=METRALE_PTX_DIR={}", out_dir.display());
    // 2026-09-25: No compiler ran, so this binary attests to no kernel
    // sources: the closure map is the empty object.
    println!("cargo:rustc-env=METRALE_TARGET_CLOSURES={{}}");
}

/// 2026-09-26: The compiling path: write `target_ptx.rs` for `targets` and
/// emit its content hash and the PTX directory.
pub(super) fn emit_generated(
    targets: &[Target],
    all_target_modules: &[Vec<(String, String)>],
    all_target_drops: &[Vec<(String, String)>],
    output_ext: &str,
    uses_cuda_api: bool,
    workspace_root: &Path,
    out_dir: &Path,
) {
    let generated = generate_target_ptx_rs(
        targets,
        all_target_modules,
        all_target_drops,
        output_ext,
        uses_cuda_api,
    );
    // 2026-09-25: The per-target serving defaults ride in the same generated file: one
    // `include!`, one content hash, one way to go stale.
    let generated = format!("{generated}{}", target_defaults_literal(workspace_root));
    let gen_path = out_dir.join("target_ptx.rs");
    std::fs::write(&gen_path, &generated)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", gen_path.display()));

    // 2026-09-25: cargo does not track this `include!`d generated file as a
    // recompile input, so the lib could embed a stale module set. The content
    // hash is passed as a rustc-env that lib.rs reads with `env!`; a changed
    // hash changes the crate's fingerprint and forces a rebuild.
    println!(
        "cargo:rustc-env=METRALE_KERNEL_SET_HASH={}",
        content_hash(&generated)
    );
    println!("cargo:rustc-env=METRALE_PTX_DIR={}", out_dir.display());
}

/// 2026-09-25: Per-target closure hashes, as one line of JSON.
///
/// Returns `{}` when the compiler cannot be identified. A target with no
/// sources, or whose closure hash fails, is left out of the map rather than
/// given a placeholder: a placeholder would let two different builds compare
/// equal. An include that names no file does not fail the hash; it is
/// reported below.
pub(super) fn closure_attestation(
    workspace_root: &std::path::Path,
    targets: &[Target],
    compute_target: &dyn build_target::ComputeTarget,
) -> String {
    let Some(compiler) = compute_target.compiler_id() else {
        return "{}".into();
    };
    let mut map = serde_json::Map::new();
    for target in targets {
        let sources = target.layout.sources();
        if sources.is_empty() {
            continue;
        }
        // 2026-09-25: Every manifest the resolution read, least specific first, framed by
        // the hardware's and the model's own declarations.
        let mut configs = vec![
            workspace_root
                .join("kernels")
                .join(&target.hw)
                .join("HARDWARE.toml"),
        ];
        configs.extend(target.layout.configs());
        configs.push(target.layout.model_dir.join("MODEL.toml"));
        let configs: Vec<PathBuf> = configs.into_iter().filter(|p| p.is_file()).collect();

        let inputs = metrale_closure::ClosureInputs {
            sources,
            configs,
            flags: target.extra_flags.clone(),
            arch: target.arch.clone(),
            compiler: compiler.clone(),
        };
        let Ok(closure) = metrale_closure::hash_with_report(workspace_root, &inputs) else {
            continue;
        };
        // 2026-09-25: Surfaced, not swallowed. A quoted include naming no file is
        // hashed by name rather than content, so a new one widens what the gate
        // cannot see. A 2026-09-25 build reported two, `vendors/hip.h` and
        // `vendors/musa.h`, under the `GGML_USE_HIP` / `GGML_USE_MUSA` arms of
        // `gb10/qwen3.6-27b/nvfp4/q4k_vendor/common.cuh`.
        for entry in &closure.unresolved {
            println!("cargo:warning=closure: unresolved include ({entry})");
        }
        map.insert(
            format!("{}/{}/{}", target.hw, target.model, target.quant),
            serde_json::json!({
                "hash": closure.digest,
                "arch": target.arch,
                "compiler": compiler,
                "flags": target.extra_flags,
            }),
        );
    }
    serde_json::Value::Object(map).to_string()
}
