// SPDX-License-Identifier: MIT OR Apache-2.0

//! 2026-09-25: Runtime loader for the GLM-5.3 reference goldens that git does not
//! track. Each is generated by the `gen_*.py` script in its directory; a missing
//! golden panics with the command that regenerates it. The small `kda_golden.json`
//! fixture is tracked, and the examples embed it with `include_str!` instead.
//!
//! Owner: model-arch examples.
//! Invariants: none beyond the types.

use std::path::PathBuf;

/// 2026-09-25: Workspace root: two levels above this crate's manifest directory.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(std::path::Path::parent)
        .expect("crates/model-arch sits two levels below the workspace root")
        .to_path_buf()
}

/// 2026-09-25: Read a golden, or panic with the command that regenerates it.
///
/// `rel` is relative to the workspace root; `generator` is the script in the
/// same directory.
pub fn load(rel: &str, generator: &str) -> String {
    let path = workspace_root().join(rel);
    match std::fs::read_to_string(&path) {
        Ok(s) => s,
        Err(e) => panic!(
            "\n\
             missing reference golden: {rel}\n\
             ({e})\n\n\
             This golden is a derived artefact and is deliberately not tracked in git.\n\
             Regenerate it with the generator beside it:\n\n    \
             python3 {dir}/{generator}\n\n\
             It needs HF transformers 5.16.1 and the GLM-5.3-Flash checkpoint; see that\n\
             script's header for the exact fixture geometry it reproduces.\n",
            rel = rel,
            e = e,
            dir = std::path::Path::new(rel).parent().unwrap().display(),
            generator = generator,
        ),
    }
}
