# Layer Gemma-4 FP32 lm_head + softcap fix on top of tp-all baseline.
#
# Build:
#   METRALE_TARGET_HW=gb10 METRALE_TARGET_MODEL='*' METRALE_TARGET_QUANT='*' \
#     cargo build --release -p spark-server
#   cp target/release/met spark-fastbin
#   docker build -f docker/gb10/Dockerfile.gemma-fp32 -t metrale-gb10:gemma-fp32 .

FROM metrale-gb10:tp-all

COPY spark-fastbin /usr/local/bin/met
COPY jinja-templates/ /jinja-templates/
